# Generated by Django 3.2.9 on 2021-11-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
