version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install virtual environment
          command: |
            python3 -m venv venv
      - run:
          name: upgrade pip
          command: |
            . venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Deployment checklist
          command: |
            . venv/bin/activate
            django check --deploy
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - run:
          name: Run coverage tests
          command: |
            . venv/bin/activate
            coverage run manage.py test
            coverage report
            coverage html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results,
      - store_artifacts:
          path: htmlcov
