# Generated by Django 3.2.9 on 2021-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
